name: CI Build

on:
  push:
    branches:
    - '*'
    - '!master'
    paths-ignore:
    - README.md
    - CHANGELOG.md

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for mvnw
        run: chmod +x mvnw

      - name: Datastore emulator install
        run: gcloud components install cloud-datastore-emulator

      - name: Build with Maven
        run: |
          gcloud beta emulators datastore start --host-port localhost:9091 --no-store-on-disk &
          export GOOGLE_CLOUD_PROJECT=test
          export DATASTORE_DATASET=hardnorth
          export DATASTORE_EMULATOR_HOST=localhost:9091
          export DATASTORE_EMULATOR_HOST_PATH=localhost:9091/datastore
          export DATASTORE_HOST=http://localhost:9091
          export DATASTORE_PROJECT_ID=test
          ./mvnw -B --no-transfer-progress test
